config/routes.rb
Rails.application.routes.draw do

  resources :rounds
  root 'tournaments#index'

  # Registration
  get 'signup', to: 'users#new', as: 'signup'

  # Authentication
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # Users
  get 'users', to: 'users#index'
  post 'users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :tournaments
  resources :players

end

app/models/player.rb
class Player < ActiveRecord::Base

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base

  # Associations
  has_many :players
  has_many :rounds

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  # Associations
  has_many :tournaments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authorize
  before_action :set_tournament, only: [:show, :new]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players/1
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    def set_tournament
      @tournament = Tournament.where('id = ?', params[:tournament_id]).first
    end

    # Only allow a trusted parameter "white list" through.
    def player_params
      params.require(:player).permit(:first_name, :last_name, :tournament_id)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authorize
  before_action :set_tournament
  before_action :set_round, only: [:show]

  # GET /rounds
  def index
    @rounds = Round.where('tournament_id = ?', @tournament.id).order(number: :asc)
  end

  # GET /rounds/1
  def show
  end

  # GET /rounds/new
  def new
    @next_round = Round.where('tournament_id = ?', @tournament.id).count + 1
    @round = Round.new
  end

  # POST /rounds
  def create
    @round = Round.new(round_params)

    if @round.save
      redirect_to round_path(@round, tournament_id: @tournament.id), notice: 'Round was successfully created.'
    else
      render :new
    end
  end

  private

    def set_round
      @round = Round.find(params[:id])
    end

    def set_tournament
      # This is kinda hacky
      if request.post?
        @tournament = Tournament.find(params[:round][:tournament_id])
      else
        @tournament = Tournament.find(params[:tournament_id])
      end
    end

    # Only allow a trusted parameter "white list" through.
    def round_params
      params.require(:round).permit(:number, :tournament_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authorize
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  def index
    Time.zone = 'Pacific Time (US & Canada)'

    @tournaments = Tournament.where('user_id = ?', current_user.id)
  end

  # GET /tournaments/1
  def show
    Time.zone = 'Pacific Time (US & Canada)'
    @user = User.find(@tournament.user_id)
    @players = Player.where('tournament_id = ?', @tournament.id)
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
    Time.zone = 'Pacific Time (US & Canada)'
  end

  # POST /tournaments
  def create
    @tournament = Tournament.new(tournament_params)

    if @tournament.save
      redirect_to @tournament, notice: 'Tournament was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tournaments/1
  def update
    if @tournament.update(tournament_params)
      redirect_to @tournament, notice: 'Tournament was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tournaments/1
  def destroy
    @tournament.destroy
    redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tournament_params
      params.require(:tournament).permit(:name, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:index, :show]
  before_action :set_user, only: [:show]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tourney</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <% if current_user %>
    Signed in as <%= current_user.first_name %> | <%= link_to 'Home', root_path %> | <%= link_to 'Log out', logout_path %>
  <% else %>
    <%= link_to 'Log in', login_path %> | <%= link_to 'Sign up', signup_path %>
  <% end %>

  <%= yield %>

  </body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :tournament_id, value: @tournament.id %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', tournament_path(@tournament) %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :tournament_id, value: @tournament.id %>

  <div class="field">
    <%= f.label :number %>: <%= @next_round %>
    <%= f.hidden_field :number, value: @next_round %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rounds for <%= @tournament.name %></h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= link_to round.number, round_path(round, tournament_id: @tournament.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path(tournament_id: @tournament.id) %>

app/views/rounds/new.html.erb
<h1>New Round</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path(tournament_id: @tournament.id) %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @round.number %>
</p>

<%= link_to 'Back', rounds_path(tournament_id: @tournament.id) %>

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: session[:user_id] %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament %></td>
        <td><%= User.find(tournament.user_id).first_name %></td>
        <td><%= tournament.created_at %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @tournament.created_at %>
</p>

<h2>Players</h2>

<p>There are <%= @players.count %> players in this tournament.</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.full_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path(tournament_id: @tournament.id) %> |
<%= link_to 'Add Player', new_player_path(tournament_id: @tournament.id) %> |
<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Back', users_path %>